version: "3.1"

services:
    mongo-db:
        image: mongo
        restart: "no"
        ports: 
            - 27017:27017
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root

    plano-service:
        image: plano/servoce
        restart: "no"
        ports: 
            - 8090:80
        depends_on: 
            - mongo-db
